import Foundation

/// The `mrkd` command is a three-line shell script that re-enters the app's own
/// executable with a sentinel argument. That keeps one implementation of the
/// command line — in Swift, inside the app — instead of a second one written in
/// shell that would drift from it.
enum CommandLineLauncher {

    /// Marks argv[1] as "this process is the command line, not the app".
    /// LaunchServices never passes it, so a GUI launch can never be mistaken
    /// for a CLI invocation.
    static let sentinel = "--mrkd-cli"

    /// Identifies a script as ours, so re-installing can replace it while an
    /// unrelated file at the same path is left alone.
    static let marker = "# mrkd command-line launcher"

    static func installURL(homeDirectory: URL) -> URL {
        homeDirectory
            .appendingPathComponent(".local")
            .appendingPathComponent("bin")
            .appendingPathComponent("mrkd")
    }

    /// The launcher for a given copy of the app.
    ///
    /// The path is canonicalised because `Bundle.main.executableURL` reports the
    /// route the process was launched by, not where the app lives: the same app
    /// is `/tmp/…` when run from a shell and `/private/tmp/…` when launched by
    /// LaunchServices. Without this the script text changes between launches and
    /// an already-installed command looks outdated every time.
    static func script(appExecutable: URL) -> String {
        script(appExecutablePath: appExecutable.resolvingSymlinksInPath().standardizedFileURL.path)
    }

    private static func script(appExecutablePath: String) -> String {
        """
        #!/bin/sh
        \(marker)
        # Generated by mrkd → Settings → Command Line. Re-run that to update it.
        MRKD_BIN=\(shellQuoted(appExecutablePath))
        if [ ! -x "$MRKD_BIN" ]; then
            echo "mrkd: cannot find mrkd.app at $MRKD_BIN — reinstall the command from mrkd Settings" >&2
            exit 1
        fi
        exec "$MRKD_BIN" \(sentinel) "$@"

        """
    }

    /// Single-quotes a value for /bin/sh, including values containing quotes.
    static func shellQuoted(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    static func displayPath(_ url: URL, homeDirectory: URL) -> String {
        let path = url.standardizedFileURL.path
        let home = homeDirectory.standardizedFileURL.path
        guard path == home || path.hasPrefix(home + "/") else { return path }
        return "~" + path.dropFirst(home.count)
    }
}

/// What is sitting at the install path right now.
enum ExistingLauncher: Equatable {
    case none
    case text(String)
    /// A directory, or bytes that are not text — nothing we can reason about.
    case opaque
}

enum LauncherInstallDecision: Equatable {
    /// Write the launcher: nothing is there, or what is there is an older
    /// launcher of ours.
    case write
    /// Byte-for-byte what we would have written.
    case alreadyInstalled
    /// Occupied by something we did not write — leave it alone.
    case refused
}

enum LauncherStatus: Equatable {
    case notInstalled
    case installed
    case outdated
    case occupied
}

/// Whether `~/.local/bin` is on the PATH the user's shell actually uses.
enum ShellPathState: Equatable {
    case onPath
    case missing
    /// The login shell could not be asked — say so rather than guess.
    case unknown
}

enum LauncherInstaller {

    static func status(existing: ExistingLauncher, desired: String) -> LauncherStatus {
        switch existing {
        case .none:
            return .notInstalled
        case .opaque:
            return .occupied
        case .text(let contents):
            if contents == desired { return .installed }
            return contents.contains(CommandLineLauncher.marker) ? .outdated : .occupied
        }
    }

    static func decide(existing: ExistingLauncher, desired: String) -> LauncherInstallDecision {
        switch status(existing: existing, desired: desired) {
        case .notInstalled, .outdated:
            return .write
        case .installed:
            return .alreadyInstalled
        case .occupied:
            return .refused
        }
    }

    static func statusText(
        status: LauncherStatus,
        displayPath: String,
        pathState: ShellPathState
    ) -> String {
        switch status {
        case .notInstalled:
            return "Not installed. Install writes the mrkd command to \(displayPath)."
        case .occupied:
            return "Another file is already at \(displayPath). mrkd will not overwrite it — move it aside first."
        case .outdated:
            return "Installed at \(displayPath), but it points at a different copy of mrkd. "
                + "Install again to update it." + pathNote(pathState, displayPath: displayPath)
        case .installed:
            return "Installed at \(displayPath)." + pathNote(pathState, displayPath: displayPath)
        }
    }

    private static func pathNote(_ state: ShellPathState, displayPath: String) -> String {
        let directory = (displayPath as NSString).deletingLastPathComponent
        switch state {
        case .onPath:
            return ""
        case .missing:
            return "\n\(directory) is not on your PATH, so the command will not be found. "
                + "Add this line to your shell profile:\n    export PATH=\"$HOME/.local/bin:$PATH\""
        case .unknown:
            return "\nCheck that \(directory) is on your shell's PATH."
        }
    }
}

/// Membership of a directory in a PATH string, spelled however the user spells
/// it. A pure comparison over values — the caller supplies the PATH.
enum ShellPath {

    static func contains(_ directory: URL, in pathVariable: String, homeDirectory: URL) -> Bool {
        let wanted = normalized(directory.path, homeDirectory: homeDirectory)
        return pathVariable
            .split(separator: ":", omittingEmptySubsequences: true)
            .contains { normalized(String($0), homeDirectory: homeDirectory) == wanted }
    }

    private static func normalized(_ entry: String, homeDirectory: URL) -> String {
        var path = entry
        if path == "~" {
            path = homeDirectory.path
        } else if path.hasPrefix("~/") {
            path = homeDirectory.path + path.dropFirst(1)
        }
        guard path.hasPrefix("/") else { return path }
        return URL(fileURLWithPath: path).standardizedFileURL.path
    }
}
